defaults:
  - /habitat/dataset: dataset_config_schema
  - /habitat/task: objectnav
  - /habitat/task/actions:
    - move_forward
    - turn_left
    - turn_right
    - look_up
    - look_down
  - /habitat/simulator/sensor_setups@habitat.simulator.agents.main_agent: rgbds_agent
  - /habitat/dataset/objectnav: hm3d
  - _self_

habitat:
  seed: 100
  environment:
    max_episode_steps: 500
    max_episode_seconds: 10000000
    iterator_options:
      shuffle: False
  dataset:
    type: ObjectNav-v1
    split: val_mini
    data_path: data/datasets/objectnav/hm3d/v2/{split}/{split}.json.gz
    scenes_dir: data/scene_datasets/
  task:
    type: ObjectNav-v1
    goal_sensor_uuid: objectgoal
  success_measurement:
    success_distance: 0.2
  simulator:
    type: Sim-v0
    turn_angle: 30
    forward_step_size: 0.25
    default_agent_id: 0
    default_agent_navmesh: True
    navmesh_include_static_objects: True
    scene: data/scene_datasets/hm3d_v0.2/minival/00800-TEEsavR23oF/TEEsavR23oF.basis.glb    
    scene_dataset: data/scene_datasets/hm3d_v0.2/hm3d_annotated_basis.scene_dataset_config.json
    additional_object_paths: []
    agents:
      main_agent:
        max_climb: 0.2
        max_slope: 45.0
        sim_sensors:
          rgb_sensor:
            width: 640
            height: 480
            hfov: 79
            position: [0, 0.88, 0]
          depth_sensor:
            width: 640
            height: 480
            hfov: 79
            min_depth: 0.5
            max_depth: 5.0
            position: [0, 0.88, 0]
          semantic_sensor:
            type: HabitatSimSemanticSensor
            width: 640
            height: 480
            hfov: 79
            position: [0, 0.88, 0]
        height: 1.41
        radius: 0.17
    renderer:
      enable_batch_renderer: False
      composite_files: null
      classic_replay_renderer: False
    habitat_sim_v0:
      gpu_device_id: 0
      gpu_gpu: False
      physics_config_file: data/default.physics_config.json
      allow_sliding: False

ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
  ITERATOR_OPTIONS:
    SHUFFLE: False
SIMULATOR:
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
  SEMANTIC_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    NORMALIZE_DEPTH: False
    MIN_DEPTH: 0.5
    MAX_DEPTH: 5.0
    POSITION: [0, 0.88, 0]

TASK:
  TYPE: ObjectNav-v1
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "LOOK_UP", "LOOK_DOWN", "TURN_RIGHT_2"]
  SUCCESS_DISTANCE: 0.2

  SENSORS: ['OBJECTGOAL_SENSOR', 'COMPASS_SENSOR', 'GPS_SENSOR']
  GOAL_SENSOR_UUID: objectgoal

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL']

  DISTANCE_TO_GOAL:
    DISTANCE_TO: VIEW_POINTS
  SUCCESS:
    SUCCESS_DISTANCE: 0.2

  